"""
Smoke Test Spider
==================
A reliable test spider that scrapes from httpbin.org - a stable test site.
This spider is designed to ALWAYS work for testing purposes.

Features:
    - Uses httpbin.org (always available)
    - Tests all middleware components
    - Tests pipeline processing
    - Generates valid NewsArticleItem items
"""

from datetime import datetime
from typing import Generator

from scrapy.http import Request, Response

from BDNewsPaper.items import NewsArticleItem
from BDNewsPaper.spiders.base_spider import BaseNewsSpider


class SmokeTestSpider(BaseNewsSpider):
    """
    Smoke test spider that uses httpbin.org for reliable testing.
    
    This spider generates synthetic but valid article items to test
    the entire pipeline without depending on external news sites.
    
    Usage:
        scrapy crawl smoketest
        scrapy crawl smoketest -a max_items=5
    """
    
    name = 'smoketest'
    paper_name = 'Smoke Test Paper'
    allowed_domains = ['httpbin.org']
    language = 'English'
    
    # API/filter capabilities
    supports_api_date_filter = False
    supports_api_category_filter = False
    
    custom_settings = {
        'DOWNLOAD_DELAY': 0.1,
        'CONCURRENT_REQUESTS_PER_DOMAIN': 2,
        'CLOSESPIDER_ITEMCOUNT': 3,  # Default to 3 items
    }
    
    def __init__(self, *args, max_items: int = 3, **kwargs):
        super().__init__(*args, **kwargs)
        self.max_items = int(max_items)
        self.items_generated = 0
        self.logger.info(f"SmokeTestSpider initialized (max_items={self.max_items})")
    
    def start_requests(self) -> Generator[Request, None, None]:
        """Generate requests to httpbin.org endpoints."""
        self.stats['requests_made'] = 0
        
        # Test different endpoints to verify request handling
        test_urls = [
            'https://httpbin.org/html',
            'https://httpbin.org/headers',
            'https://httpbin.org/user-agent',
        ]
        
        for url in test_urls[:self.max_items]:
            self.stats['requests_made'] += 1
            yield Request(
                url=url,
                callback=self.parse_test_page,
                meta={'test_id': self.stats['requests_made']},
                errback=self.handle_request_failure,
            )
    
    def parse_test_page(self, response: Response) -> Generator[NewsArticleItem, None, None]:
        """Parse test page and generate synthetic article item."""
        if self.items_generated >= self.max_items:
            return
        
        test_id = response.meta.get('test_id', 1)
        
        # Generate a valid article item
        headline = f"Smoke Test Article #{test_id}: Testing Complete Pipeline"
        
        # Create realistic article body
        article_body = f"""
        This is a smoke test article generated by the SmokeTestSpider.
        
        The purpose of this test is to verify that all middleware and pipeline
        components are working correctly. This article was generated from
        URL: {response.url}
        
        Response status: {response.status}
        Response length: {len(response.body)} bytes
        
        Test ID: {test_id}
        Timestamp: {datetime.now().isoformat()}
        
        This body contains sufficient content to pass validation pipelines.
        The minimum required length is typically 50-100 characters.
        This text ensures we exceed that threshold comfortably.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
        """
        
        # Verify response is valid
        if response.status != 200:
            self.logger.warning(f"Non-200 status from {response.url}: {response.status}")
            return
        
        self.stats['articles_found'] += 1
        self.items_generated += 1
        self.stats['articles_processed'] += 1
        
        yield self.create_article_item(
            url=response.url,
            headline=headline,
            article_body=article_body.strip(),
            publication_date=datetime.now().isoformat(),
            category='Test',
            author='SmokeTestSpider',
            image_url='https://httpbin.org/image/png',
        )
