#!/usr/bin/env python3
"""
Telegram Bot for News Notifications
====================================
Sends daily news summaries to Telegram.

Setup:
    1. Create a bot via @BotFather on Telegram
    2. Get your bot token
    3. Get your chat ID (use @userinfobot)
    4. Set environment variables:
       export TELEGRAM_BOT_TOKEN="your-token"
       export TELEGRAM_CHAT_ID="your-chat-id"

Usage:
    python telegram_bot.py                # Send today's summary
    python telegram_bot.py --days 7       # Send last 7 days summary
    python telegram_bot.py --paper "Prothom Alo"  # Specific paper
    python telegram_bot.py --schedule     # Run as scheduled service
"""

import argparse
import os
import sqlite3
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
from urllib.request import Request, urlopen
from urllib.error import URLError
import json


DB_PATH = Path(__file__).resolve().parent.parent / "news_articles.db"

# Telegram credentials from environment
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")


def send_telegram_message(text: str, parse_mode: str = "HTML") -> bool:
    """Send message to Telegram chat."""
    if not BOT_TOKEN or not CHAT_ID:
        print("❌ Telegram credentials not set!")
        print("   Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID environment variables")
        return False
    
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    
    # Telegram has 4096 character limit
    if len(text) > 4000:
        text = text[:4000] + "\n\n... (truncated)"
    
    data = json.dumps({
        "chat_id": CHAT_ID,
        "text": text,
        "parse_mode": parse_mode,
        "disable_web_page_preview": True
    }).encode("utf-8")
    
    try:
        req = Request(url, data=data, headers={"Content-Type": "application/json"})
        with urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode())
            if result.get("ok"):
                print("✅ Message sent to Telegram")
                return True
            else:
                print(f"❌ Telegram API error: {result}")
                return False
    except URLError as e:
        print(f"❌ Failed to send message: {e}")
        return False


def get_news_summary(
    days: int = 1,
    paper_name: Optional[str] = None,
    limit: int = 20
) -> str:
    """Generate news summary from database."""
    
    if not DB_PATH.exists():
        return "❌ Database not found. Run some spiders first!"
    
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    
    cutoff = (datetime.now() - timedelta(days=days)).isoformat()
    
    # Get article counts by paper
    query = """
        SELECT paper_name, COUNT(*) as count 
        FROM articles 
        WHERE scraped_at >= ?
    """
    params = [cutoff]
    
    if paper_name:
        query += " AND paper_name = ?"
        params.append(paper_name)
    
    query += " GROUP BY paper_name ORDER BY count DESC"
    
    stats = conn.execute(query, params).fetchall()
    total = sum(row["count"] for row in stats)
    
    if total == 0:
        return f"📭 No articles found in the last {days} day(s)."
    
    # Get top headlines
    headline_query = """
        SELECT headline, paper_name, url, category
        FROM articles 
        WHERE scraped_at >= ?
    """
    headline_params = [cutoff]
    
    if paper_name:
        headline_query += " AND paper_name = ?"
        headline_params.append(paper_name)
    
    headline_query += " ORDER BY scraped_at DESC LIMIT ?"
    headline_params.append(limit)
    
    headlines = conn.execute(headline_query, headline_params).fetchall()
    
    conn.close()
    
    # Build message
    today = datetime.now().strftime("%B %d, %Y")
    period = f"Last {days} day(s)" if days > 1 else "Today"
    
    msg = f"🗞️ <b>BD News Summary</b>\n"
    msg += f"📅 {today} | {period}\n"
    msg += f"📊 <b>{total}</b> articles collected\n\n"
    
    # Stats by paper
    msg += "📰 <b>By Newspaper:</b>\n"
    for row in stats[:10]:
        msg += f"  • {row['paper_name']}: {row['count']}\n"
    
    if len(stats) > 10:
        msg += f"  ... and {len(stats) - 10} more\n"
    
    # Top headlines
    msg += "\n📌 <b>Latest Headlines:</b>\n\n"
    for i, h in enumerate(headlines[:10], 1):
        headline = h["headline"][:100] + "..." if len(h["headline"]) > 100 else h["headline"]
        msg += f"{i}. <a href=\"{h['url']}\">{headline}</a>\n"
        msg += f"   <i>— {h['paper_name']}</i>\n\n"
    
    msg += "\n🔗 <i>Generated by BDNewsPaperScraper</i>"
    
    return msg


def run_scheduled(interval_hours: int = 24):
    """Run as a scheduled service."""
    print(f"🕐 Running scheduled notifications every {interval_hours} hours")
    print("   Press Ctrl+C to stop")
    
    while True:
        try:
            summary = get_news_summary(days=1)
            send_telegram_message(summary)
            
            print(f"💤 Sleeping for {interval_hours} hours...")
            time.sleep(interval_hours * 3600)
            
        except KeyboardInterrupt:
            print("\n👋 Stopping scheduler")
            break


def main():
    parser = argparse.ArgumentParser(description="Send news summaries to Telegram")
    parser.add_argument("--days", type=int, default=1, help="Number of days to summarize")
    parser.add_argument("--paper", help="Specific newspaper")
    parser.add_argument("--limit", type=int, default=20, help="Max headlines to include")
    parser.add_argument("--schedule", action="store_true", help="Run as scheduled service")
    parser.add_argument("--interval", type=int, default=24, help="Schedule interval in hours")
    parser.add_argument("--test", action="store_true", help="Print summary without sending")
    
    args = parser.parse_args()
    
    if args.schedule:
        run_scheduled(args.interval)
    else:
        summary = get_news_summary(
            days=args.days,
            paper_name=args.paper,
            limit=args.limit
        )
        
        if args.test:
            print(summary.replace("<b>", "").replace("</b>", "")
                       .replace("<i>", "").replace("</i>", "")
                       .replace("<a href=\"", "[").replace("\">", "](").replace("</a>", ")"))
        else:
            send_telegram_message(summary)


if __name__ == "__main__":
    main()
